# Generated by Django 2.2.1 on 2019-05-08 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='is_staff',
        ),
    ]
