# Generated by Django 2.2.1 on 2019-05-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_mainuser_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App',
        ),
    ]
