# Generated by Django 2.2.1 on 2019-05-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190515_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
