# Generated by Django 2.2.1 on 2019-05-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190515_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
