# Generated by Django 2.2.1 on 2019-05-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dish_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
    ]
